### ISSUE TITLE
Problemas en la normalizacion de cadenas.

### ISSUE THREAD

**Issue by PabloSoligo2014** [PabloSoligo2014/TPI2019C2#1]
La prueba 03 desnormalizacion de cadenas falla. Desarrollado por @perpetuaReality.

**Comment by perpetuaReality** [comment]
La función de normalización de cadenas ha sido alterada para tomar en cuenta los casos en que no se proveea la coma después del apellido pero si haya un solo espacio después de este. Como resultado, ahora la prueba 03, tanto como las nuevas 04, 05, 06 y 07 retornan OK.
